### ISSUE TITLE
Cannot find *.jar in lib

### ISSUE THREAD

**Issue by nuaa040840308** [mohrm/android-analyzer#11]
Sorry, I cannot find the json.jar, joana.api.jar, joana.wala.jodroid,jar in Analyzer/lib.  Why?

**Comment by mohrm** [comment]
Because you haven't done everything not mentioned in the [README](https://github.com/mohrm/android-analyzer/blob/master/README) :-)
After initializing all submodules, you should invoke "ant" to build the jars.

**Comment by nuaa040840308** [comment]
OK，thanks a lot.
