### ISSUE TITLE
Question in ShortAnalysis.java

### ISSUE THREAD

**Issue by nuaa040840308** [mohrm/android-analyzer#12]
I have built Joana successfully. However, when running ShortAnalysis.java, I encountered a problem:
![7io i s3m3793wnr 5h3s8](https://cloud.githubusercontent.com/assets/13410137/11455763/4ea44d84-96a9-11e5-8d46-c55c9baea8ee.jpg)

**Comment by mohrm** [comment]
Looking at your line numbers, I think that your Joana version is outdated. Please make sure that 
(a) you checked out the most recent versions of all submodules
(b) you have built all libs from these versions
In 4d63c6c, I solved another problem which would result in a later crash. So if you check out the latest version and rebuild the libs, it should not crash anymore!

**Comment by mohrm** [comment]
I think this one is clarified.
